### ISSUE TITLE
Inspect

### ISSUE THREAD

**Issue by l2xBrain** [XadillaX/nyaa-nodejs-demo#1]
在 Chrome浏览器中输入 `
const obj = { foo: 1 };
obj.inspect = function(){ return "覆盖输出" }
console.log(obj);
`
结果并不是覆盖输出。
在node REPL 中结果是覆盖输出。是Chrome浏览器对输出做处理了吗？

**Comment by XadillaX** [comment]
以 Node.js 10.8.0 为例，`console.log` 的代码是：

```js
Console.prototype.log = function log(...args) {
  write(this._ignoreErrors,
        this._stdout,
        this[kFormatForStdout](args),
        this._stdoutErrorHandler,
        this[kGroupIndent]);
};
```

你传入的参数经过了 `this[kFormatForStdout](...)` 处理，而这个函数是这样的：

```js
Console.prototype[kFormatForStdout] = function(args) {
  const opts = this[kGetInspectOptions](this._stdout);
  return util.formatWithOptions(opts, ...args);
};
```

先根据 `stdout` 获取一些配置，如在 TTY 下和非 TTY 下的输出是不同的。然后接下去就是 `util.formatWithOptions(opts, ...args)` 来格式化输出了，这个 `util` 就是 Node.js 的 `util` 模块。

我们甚至都不需要读代码，直接看文档：

> ## util.formatWithOptions(inspectOptions, format[, ...args])#
>
> Added in: v10.0.0
>
> + `inspectOptions` [<Object>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
> + `format` [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)
>
> This function is identical to [util.format()](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_format_format_args), except in that it takes an inspectOptions argument which specifies options that are passed along to [util.inspect()](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_inspect_object_options).
>
> ```js
> util.formatWithOptions({ colors: true }, 'See object %O', { foo: 42 });
> // Returns 'See object { foo: 42 }', where `42` is colored as a number
> // when printed to a terminal.
> ```

这么一看就明白了吧。

至于这里面具体的实现，最后追溯到这么[一段代码](https://github.com/nodejs/node/blob/v10.8.0/lib/util.js#L453-L460)：

```js
    if (!maybeCustom && value.inspect !== exports.inspect &&
        typeof value.inspect === 'function') {
      maybeCustom = deprecate(
        value.inspect,
        'Custom inspection function on Objects via .inspect() is deprecated',
        'DEP0079'
      );
    }
```

至少，在 Node.js 10 中，它被标记为即将被弃用的 API 了，以后最好是通过 `util.inspect. custom` 来定义：

```js
{
    [util.inspect.custom]: function(...) { ... }
}
```
